### ISSUE TITLE
6 символов

### ISSUE THREAD

**Issue by rsking01** [eremeyko/vkcomCaptchaBreaker#2]
Приветствую, заметил, что капча на стене не решается из-за того, что в ней 6 символов. Можно ли это как-то исправить?

**Comment by Enrypint** [comment]
Судя по оригинальному коду, модель обучалась на данных 4-5 символов, так что никак не получиться исправить, если только не переобучить модель (но кто этим займется).

![изображение](https://user-images.githubusercontent.com/110914335/185698847-1c0b2d3c-693d-4c42-a4ed-82e76c181a63.png)

Автор походу сдох, не отвечает и не активничает. Кст, оцени мой коммит с исправлением распознавания капчи

**Comment by eremeyko** [comment]
> Судя по оригинальному коду, модель обучалась на данных 4-5 символов

Всё верно, модели были обучены на ограниченной версии капчи. Но её можно отредактировать, чтобы он и 6-значную капчу "хавал"

> Автор походу сдох, не отвечает и не активничает. 

Не обессудь, занимаюсь уже твоим фиксом с:
