### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by miztizm** [eremeyko/vkcomCaptchaBreaker#3]
Вылазит варн в секции расширений хрома:

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by Enrypint** [comment]
и что? Это же всего варн. Вообще реально поддержку отключат в 2024 году, а потом можно будет перейти на нормальные браузеры, ну например firefox, которые не будут ограничивать свободу пользователя просто так. 
https://developer.chrome.com/docs/extensions/mv3/intro/#start-the-conversion
С 17 января 2022 г. Интернет-магазин Chrome прекратил прием новых расширений Manifest V2. Мы настоятельно рекомендуем как можно скорее перенести ваши расширения на Manifest V3; это станет обязательным после [прекращения использования Manifest V2 ](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)в 2024 году.

**Comment by miztizm** [comment]
да ничего в общем то, репортю, в чем сложность обновить?

**Comment by eremeyko** [comment]
> в чем сложность обновить?

Обновлял, но сюда не загрузил, так как не посчитал важным. Оно реализовано, к примеру, в магазине расширений Firefox.
Отложил "на потом" до лучших времён
