### ISSUE TITLE
перестало работать

### ISSUE THREAD

**Issue by miztizm** [eremeyko/vkcomCaptchaBreaker#4]
не решает капчу:

![image](https://github.com/eremeyko/vkCaptchaBreaker/assets/617020/922807c1-73e9-4a76-b0bb-1963edd27620)
![image](https://github.com/eremeyko/vkCaptchaBreaker/assets/617020/a455845e-29ab-4011-b613-d1bc25f7ec35)

**Comment by Enrypint** [comment]
прикрыли лавочку((((( 
решается банально задержкой как я понял, потому что стали чекать скорость решения капчи

**Comment by Enrypint** [comment]
я потыкал, добавление задержки 2 секунды перед отправкой решает проблему
что-то типо `await new Promise(r => setTimeout(r, 2000));`

**Comment by miztizm** [comment]
@Enrypint оо ты зверь спасибо за наводку, попробовал работает ;)

```
     if (click) {
             // Wait for 2 seconds before submitting
                await new Promise(r => setTimeout(r, 2000));
                submit_button.click();
            try {
                const captcha_img = captchaForm[num].getElementsByTagName('img')[0];
                if (captcha_img.length) {
                    if (captcha_img.src[0] !== 'd') {
                        bool_recognized = false;
                    }
                }
            } catch (e) {
                console.log(e);
                bool_recognized = true;
            }
            return bool_recognized;
        }
```

**Comment by eremeyko** [comment]
> попробовал работает ;)

Добавил, прикрутил рандомную вариативность секунд
Сейчас буду обучать модельки на русскую капчу, чтобы впн/прокси не юзать

**Comment by eremeyko** [comment]
Теперь работает. Используйте VPN для английской капчи. Насчёт русской работаю
